name: Generate Snake

on:
  schedule: # roda automaticamente a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: caiomccunha
          output: snake.svg

      # 3️⃣ Commit e push da cobrinha para a branch 'output'
      - name: Push Snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Update snake animation"
          add: "snake.svg"
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
